project:
  type: website
  output-dir: docs

website:
  title: "Jonny's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jonnycomes
      - icon: linkedin
        href: https://linkedin.com/jcomes
format:
  html:
    theme: united
    css: styles.css



